services: 
  redis: 
    image: redis:7.4-alpine
    container_name: redis-chat
    ports: 
      - "6379:6379"
    volumes: 
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  database:
    image: postgres:15-alpine
    container_name: db
    mem_limit: 512m
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./db_script.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  redis_data:
  database_data:

networks:
  backend:
    driver: bridge